# Use root/example as user/password credentials
version: '3.1'

services:

  mysql_db:
    image: mysql
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - devdojo_data:/var/lib/mysql

  adminer_mysql:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  devdojo_data: